# **Stroke Predictor App- Data ETL process**

## Objectives

* Extract dataset from Kaggle and import into notebook
* Push data through ETL pipeline to clean data using pandas and numpy where required
* Export clean data to "Clean Data" folder

## Inputs

* Dataset from the "Raw Data" file, imported from Kaggle

## Outputs

* Clean Data, stored in "Clean Data" file

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\naqas\\OneDrive\\Documents\\Coding\\CI_Projects\\stroke_prediction_app\\stroke_prediction_app\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\naqas\\OneDrive\\Documents\\Coding\\CI_Projects\\stroke_prediction_app\\stroke_prediction_app'

## Import required packages for ETL

First, packages are required to be imported for the ETL pipeline

In [4]:
import numpy as np
import pandas as pd

---

## Import and clean dataset

Next, the dataset must be imported as a dataframe.

In [5]:
stroke_dataset_df = pd.read_csv("data_Files/RawData/healthcare-dataset-stroke-data.csv")
stroke_dataset_df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

---

Next, the information of the dataset is required to determine the columns and their data types.

In [6]:
stroke_dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   object
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   object
 6   work_type          5110 non-null   object
 7   Residence_type     5110 non-null   object
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB

Next, it must be determined if any columns have any null values.

In [7]:
stroke_dataset_df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

The only column that contained any null values was the "BMI" column. These rows can be dropped as BMI can not be imputed based off the other columns in the dataset.

In [8]:
stroke_dataset_df= stroke_dataset_df.dropna()
stroke_dataset_df.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

Now there are no null values in the data, the next thing to do is to remove the "id" column. This column will not be relevant to any of the visualisation or analysis and so it is better to remove this.

In [9]:
stroke_dataset_df = stroke_dataset_df.drop(labels=["id"], axis = 1)
stroke_dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4909 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             4909 non-null   object
 1   age                4909 non-null   float64
 2   hypertension       4909 non-null   int64
 3   heart_disease      4909 non-null   int64
 4   ever_married       4909 non-null   object
 5   work_type          4909 non-null   object
 6   Residence_type     4909 non-null   object
 7   avg_glucose_level  4909 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     4909 non-null   object
 10  stroke             4909 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 460.2+ KB

Next, it is important to make sure the data has the correct types. "Age" is currently a float, however, it should be an integer for.

In [10]:
stroke_dataset_df = stroke_dataset_df.astype({"age":"int"})
stroke_dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4909 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             4909 non-null   object
 1   age                4909 non-null   int32
 2   hypertension       4909 non-null   int64
 3   heart_disease      4909 non-null   int64
 4   ever_married       4909 non-null   object
 5   work_type          4909 non-null   object
 6   Residence_type     4909 non-null   object
 7   avg_glucose_level  4909 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     4909 non-null   object
 10  stroke             4909 non-null   int64
dtypes: float64(2), int32(1), int64(3), object(5)
memory usage: 441.0+ KB

In [11]:
stroke_dataset_df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
2,Male,80,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,Male,81,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
5104,Female,13,0,0,No,children,Rural,103.08,18.6,Unknown,0
5106,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,Male,51,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,Female,44,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

From the source where the dataset is derived, it was mentioned that the "Gender" column has a third value of "Other" and the "Smoking status" column has an extra value of "unknown". The value of "other" has to be removed as it is too vague an answer and so incorrect correlations could be derived from generalising "other". "Unknown" must be removed as it will provide no value to predicting stroke likelihood. By knowing if a patient was a smoker or not can help determine the impact of smoking on stroke occurrence probability.

In [12]:
stroke_dataset_df = stroke_dataset_df[stroke_dataset_df["gender"] != "Other"]
stroke_dataset_df["gender"].unique()

array(['Male', 'Female'], dtype=object)

By running the "unique()" method we can see that the only remaining unique values for the "gender" column

In [13]:
stroke_dataset_df = stroke_dataset_df[stroke_dataset_df["smoking_status"] != "Unknown"]
stroke_dataset_df["smoking_status"].unique()

array(['formerly smoked', 'never smoked', 'smokes'], dtype=object)

The same method has been implemented for the "Smoking status" column to remove the "Unknown" values.

In [14]:
stroke_dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3425 entries, 0 to 5108
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             3425 non-null   object
 1   age                3425 non-null   int32
 2   hypertension       3425 non-null   int64
 3   heart_disease      3425 non-null   int64
 4   ever_married       3425 non-null   object
 5   work_type          3425 non-null   object
 6   Residence_type     3425 non-null   object
 7   avg_glucose_level  3425 non-null   float64
 8   bmi                3425 non-null   float64
 9   smoking_status     3425 non-null   object
 10  stroke             3425 non-null   int64
dtypes: float64(2), int32(1), int64(3), object(5)
memory usage: 307.7+ KB

In [15]:
stroke_dataset_df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
2,Male,80,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,Female,49,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,Female,79,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
5,Male,81,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [16]:
stroke_dataset_df.tail()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
5100,Male,82,1,0,Yes,Self-employed,Rural,71.97,28.3,never smoked,0
5102,Female,57,0,0,Yes,Private,Rural,77.93,21.7,never smoked,0
5106,Female,81,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,Female,35,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,Male,51,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0

In [17]:
stroke_dataset_df.duplicated().sum()

0

A final assessment of the data is completed with snippets of the top and bottom of the datasets using the "head()" and "tail()" methods and a final check for any duplicated data.

---

## Export Clean Data

In [20]:
stroke_dataset_df.to_csv("data_files/CleanData/stroke_data_clean.csv", index=False)

The dataset has been cleaned and exported to the "Clean Data" folder ready for visualisation.

---

# Conclusion

The initial data was not too complex to clean and so the rationale and process chosen was as follows:

* After the first null count analysis it was determined that only the "BMI" column had any null values. These rows had to be removed as "BMI" can not be predicted based off the other variables present in the dataset.
* Once the null values were removed, the dataset was analysed again on the datatypes of each variable. "Age" was a float and this was the only datatype that needed changing to an integer as "Age" is not a continuous variable.
* The next change implemented was the removal of the "id" column as this provides no value for modelling or analysis and will only cause issues later on down the line.
* It was then determined that both the "Gender" and "Smoking status" columns contained data values ("other" and "unknown" respectively) that were too vague and did not provide specific information on the impact on stroke probability. As a result, the rows containing these values were removed.
* Once all these changes were done, the dataset had one final analysis (head, tail and duplicates) and was exported as a clean data set ready for visualising the data in the next step